### ISSUE TITLE
gh-pages isn't created by default

### ISSUE THREAD

**Issue by Manoz** [jlord/person-page#1]
Hi, nice work. I wanted to build a similar personal page with all my social media things and sheetsee.js. You did it for me :)

Btw, just wanted to warn you that your forgot to create the `gh-pages` . I had to create it myself but it works fine \o/

**Comment by Manoz** [comment]
Oh and I think your Instagram recipe isn't good. It add photos on a gDrive folder but just the .jpg. It didn't create a spreadsheet. The good recipe should be something like [this](https://ifttt.com/recipes/179322-add-my-instagram-photos-to-a-spreadsheet). (didn't tested it)

**Comment by jlord** [comment]
@Manoz So sorry I'm just now seeing this. Forgot that you have to 'watch' your own repos :/ so I didn't get the notification. 

I recently realized the gh-pages thing myself, I'd made the branch but not gotten rid of master and made gh-pages the only and default branch. Glad you figured it out though!

Thanks for pointing out the Instagram link! I have both recipes and linked to the wrong one :) I'll update it now!

Thanks!!
